/*
<MODULE_CONTRACT>
<purpose>Creates, validates, and explains ancestry records tracking canonical inputs, mutations, and constraint outcomes for laboratory seeds.</purpose>
<non-goals>
  <item>Does not create seeds — ancestry records only.</item>
</non-goals>
</MODULE_CONTRACT>
<CHANGE_SUMMARY>
  <item>Initial creation: AncestryRecord, createAncestry, validateAncestry, explainAncestry.</item>
</CHANGE_SUMMARY>
*/
import { isCanonicalRecordId, isLaboratoryRecordId } from "./schema.ts";
import type { GeneratorMetadata } from "./schema.ts";
import type { MutationResult } from "./mutation.ts";
import type { ConstraintCheckResult } from "./constraints.ts";

export interface AncestryRecord {
  canonical_input_ids: string[];
  mutation_vector_ids: string[];
  transformations: string[];
  constraints_satisfied: string[];
  constraints_violated: string[];
  generator_metadata: GeneratorMetadata;
}

export interface AncestryValidationResult {
  valid: boolean;
  errors: string[];
}

export function createAncestry(
  canonicalInputIds: string[],
  mutationResults: MutationResult[],
  constraintCheck: ConstraintCheckResult,
  generatorMetadata: GeneratorMetadata,
): AncestryRecord {
  return {
    canonical_input_ids: [...canonicalInputIds],
    mutation_vector_ids: mutationResults.map((r) => r.vector_id),
    transformations: mutationResults.map((r) => r.transformation),
    constraints_satisfied: constraintCheck.satisfied,
    constraints_violated: constraintCheck.violated,
    generator_metadata: generatorMetadata,
  };
}

export function validateAncestry(
  ancestry: AncestryRecord,
  seedId: string,
): AncestryValidationResult {
  const errors: string[] = [];

  for (const ref of ancestry.canonical_input_ids) {
    if (!isCanonicalRecordId(ref)) {
      errors.push(`Ancestry canonical_input_id '${ref}' is not a valid canonical record id`);
    }
    if (isLaboratoryRecordId(ref)) {
      errors.push(`Ancestry canonical_input_id '${ref}' is a laboratory id — seeds may only reference canonical records as ancestry`);
    }
  }

  if (ancestry.canonical_input_ids.includes(seedId)) {
    errors.push(`Seed ${seedId} cannot reference itself in ancestry`);
  }

  for (const ref of ancestry.canonical_input_ids) {
    if (ref === seedId) {
      errors.push(`Seed ${seedId}: self-reference in ancestry`);
    }
  }

  return { valid: errors.length === 0, errors };
}

export interface AncestryExplanation {
  summary: string;
  canonical_ingredients: string[];
  mutations_applied: string[];
  constraints: { satisfied: string[]; violated: string[] };
  generator_info: string;
}

export function explainAncestry(ancestry: AncestryRecord): AncestryExplanation {
  const canonicalIngredients = ancestry.canonical_input_ids.map(
    (id) => `canonical:${id}`,
  );
  const mutationsApplied = ancestry.transformations;
  const generatorInfo = ancestry.generator_metadata.provider
    ? `Generated by ${ancestry.generator_metadata.provider}/${ancestry.generator_metadata.model} (template: ${ancestry.generator_metadata.template_version})`
    : "Generated by deterministic pipeline (no AI provider)";

  const summary = `Seed derived from ${ancestry.canonical_input_ids.length} canonical input(s), ${ancestry.transformations.length} mutation(s). ${generatorInfo}.`;

  return {
    summary,
    canonical_ingredients: canonicalIngredients,
    mutations_applied: mutationsApplied,
    constraints: {
      satisfied: ancestry.constraints_satisfied,
      violated: ancestry.constraints_violated,
    },
    generator_info: generatorInfo,
  };
}
